// <auto-generated />
using System;
using HospitalReceipts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalReceipts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819105520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("HospitalReceipts.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Printed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceiptBookMainBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceiptNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Towards")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceiptId");

                    b.HasIndex("BookId");

                    b.HasIndex("ReceiptBookMainBookId");

                    b.ToTable("Receipt", (string)null);
                });

            modelBuilder.Entity("HospitalReceipts.Models.ReceiptBookMain", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTowards")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header3")
                        .HasColumnType("TEXT");

                    b.Property<int>("NextReceiptNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId");

                    b.ToTable("ReceiptBookMain", (string)null);
                });

            modelBuilder.Entity("HospitalReceipts.Models.Receipt", b =>
                {
                    b.HasOne("HospitalReceipts.Models.ReceiptBookMain", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalReceipts.Models.ReceiptBookMain", "ReceiptBookMain")
                        .WithMany()
                        .HasForeignKey("ReceiptBookMainBookId");

                    b.Navigation("ReceiptBookMain");
                });
#pragma warning restore 612, 618
        }
    }
}
